
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - readme.md

pr:
- master
- develop

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:

# do this before all your .NET Core tasks
steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 2.2.x
# ...

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
