trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - readme.md

pr:
- master
- develop

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  sdkVersion: '2.2.x'


steps:
- task: UseDotNet@2
  inputs:
    version: $(sdkVersion)
  displayName: 'Install .NET Core SDK'

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.csproj'
  displayName: 'Restore nuget packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    configuration: '$(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'
