
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - readme.md

pr:
- master
- develop

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  sdkVersion: '2.2.x'


steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: $(sdkVersion)

- task: DotNetCoreCLI@2
  inputs:
    command: 'build --configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'
